name: brew test-bot

on:
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os:
          # - macos-15            # Apple Silicon
          # - macos-15-intel      # Intel
          # - ubuntu-22.04-arm64  # Linux arm64
          - ubuntu-22.04        # Linux x86_64

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      checks: read
      contents: read
      packages: read
      pull-requests: read

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
      BOTTLES_DIR: ${{ github.workspace }}/bottles

    steps:

      - name: Pre-build
        uses: Homebrew/actions/pre-build@main
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}

      - working-directory: ${{ env.BOTTLES_DIR }}
        run: |
          brew test-bot \
            --only-formulae \
            --skip-online-checks \
            --skip-dependents \
            --root-url=https://ghcr.io/v2/mad0x20wizard/test

      - name: Post-build
        uses: Homebrew/actions/post-build@main
        with:
          runner: ${{ matrix.os }}
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ env.BOTTLES_DIR }}/logs

  label-pr:
    name: Label PR for publishing bottles
    needs: test-bot
    runs-on: ubuntu-22.04

    permissions:
      pull-requests: write

    steps:
      - name: Add pr-pull label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["pr-pull"]
            })