name: brew test-bot

on:
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os:
          # - macos-15            # Apple Silicon
          # - macos-15-intel      # Intel
          - ubuntu-24.04-arm64  # Linux arm64
          - ubuntu-24.04        # Linux x86_64

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      checks: read
      contents: read
      packages: read
      pull-requests: read

    # env:
    #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #   HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #   BOTTLES_DIR: ${{ github.workspace }}/bottles

    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax

      - run: |
          brew test-bot \
            --only-formulae \
            --skip-online-checks \
            --skip-dependents \
            --root-url=https://ghcr.io/v2/mad0x20wizard/test

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'

  label-pr:
    name: Label PR for publishing bottles
    needs: test-bot
    runs-on: ubuntu-22.04

    permissions:
      pull-requests: write

    steps:
      - name: Add pr-pull label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["pr-pull"]
            })